#!/usr/bin/sh

# Pedro Binotto, 2025
# Read PDF document as plain text inside terminal pager

PROGNAME=$(basename $0);

if [ -z "${1}" ]; then
    echo "USAGE: ${PROGNAME} <TARGET>";
    exit 1;
fi

echo ${1};
pdftotext -layout "${1}" - | less

