#!/bin/sh

# Pedro Binotto, 2025
# Print small help message concerning the keybinds and aliases set by
# configuration script

cat << EOF

Ctrl-f ........................................................ sessionizer

Alt-a ..... -> sessionizer ... ~/projetos/bridge/sgtes-residencias/frontend
Alt-s ..... -> sessionizer ................. ~/projetos/bridge/pec/frontend
Alt-j ..... -> sessionizer ....................... ~/.dotfiles/shellscripts
Alt-k ..... -> sessionizer .................................... ~/.dotfiles

zshconfig . -> \$EDITOR ........................................... ~/.zshrc
kittyconfig -> \$EDITOR ......................... ~/.config/kitty/kitty.conf
vimconfig . -> \$EDITOR ............................ ~/.config/nvim/init.vim
:q ................................................................... exit

EOF

