#!/usr/bin/bash

PROGNAME=$(basename $0);

NC='\033[0m'
YELLOW='\033[1;33m'
GREEN='\033[1;32m'
BLUE='\033[0;34m'
RED='\033[1;31m'

if [ -z "${1}" ]; then
    # TODO: mensagem de ajuda
    echo "USAGE: ${PROGNAME} [TARGET DIR]";
    exit 1;
elif [ ! -d "${1}" ]; then
    echo "${PROGNAME}: ${1}: Not a directory.";
    exit 1;
fi

cat << "EOF"
     _           _
  __| | ___  ___| |_ _____      __
 / _` |/ _ \/ __| __/ _ \ \ /\ / /
| (_| |  __/\__ \ || (_) \ V  V /
 \__,_|\___||___/\__\___/ \_/\_/

EOF

while true; do
    echo 'Packages to be stowed:'
    for PACKAGE in * ; do
        printf "${BLUE}${PACKAGE}${NC}\n"
    done
    read -p "Proceed? (y/n) " yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit 0;;
        * ) echo "Please answer y/n.";;
    esac
done

declare -a SUCCESS
declare -a FAILURE

for PACKAGE in * ; do
    stow -nvt ~ ${PACKAGE}
    if [ $? == 0 ]; then
        SUCCESS+=(${PACKAGE})
        printf "${GREEN}${PROGNAME}${NC}: package [${PACKAGE}] stowed succesfully.\n"
    else
        FAILURE+=(${PACKAGE})
        printf "${YELLOW}${PROGNAME}${NC}: failed to stow package [${RED}${PACKAGE}${NC}].\n"
    fi
done


printf "\n\033[1m${#SUCCESS[@]}${NC} packages stowed succesfully;\n"
for PACKAGE in ${SUCCESS[*]} ; do
    printf "${GREEN}${PACKAGE}${NC}\n"
done
printf "\n"

printf "\033[1m${#FAILURE[@]}${NC} packages failed to be stowed;\n"
for PACKAGE in ${FAILURE[*]} ; do
    printf "${RED}${PACKAGE}${NC}\n"
done
printf "\n"

exit 0

