#!/bin/sh


if ! mpc >/dev/null 2>&1; then
  echo Server offline
  exit 1
elif mpc status | grep -q playing; then
    mpc status -f %title% | awk 'NR==1{print $0}'
else
  echo Not playing
fi
mpc idle >/dev/null
