#!/bin/bash

PROGNAME=$(basename $0);

if (("$#" < 1)) || (("$#" > 2)); then
    echo "USAGE: ${PROGNAME} <file>";
    exit 1;
fi

FILE=$1;
FILE_EXT=$(echo $FILE |awk -F . '{if (NF>1) {print $NF}}')

if [ $FILE_EXT != 'tex' ]; then
    echo "Invalid file extension. Must be .tex file"
    exit 1;
fi;

cd dirname $FILE
rm -rf *.pdf *.log *.aux *.bbl
xelatex $FILE
bibtex $(echo "$FILE" | cut -f 1 -d '.'
xelatex $FILE
xelatex $FILE

